apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label }}
  labels:
    app: {{ .Values.label }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.label }}
      
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
        tier: {{ .Values.label }}
    spec:
      containers:
        - name: my-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080S
