apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label }}
  labels:
    app: {{ .Values.label }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.label }}
    tier: {{ .Values.label }}
  type: {{ .Values.service.type }}
