apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: my-app
  newName: mynamesandesh/argocd-demo
  newTag: d75165a3dc580a3a8b29fe6989d80a2d68a31ee6
