apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: my-app
  newName: mynamesandesh/argocd-demo
  newTag: 959949929637cf2a1f6cd27bee86aa21a943aa51
