apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: my-app
  newName: docker.io/mynamesandesh/argocd-demo
  newTag: 819da29142ab281842a7f1a58dadd2aac4063fae
