apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml
images:
- name: demo
  newName: mynamesandesh/argocd-demo
  newTag: dde6b73b20951cedf5032bec3b4f07f9f6940ff4
