apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

resources:
- ../base
images:
- name: hello
  newName: mynamesandesh/argocd-demo
  newTag: d16b429cbba811167292410ea24503d25e4c039f
- name: mynamesandesh/argocd-demo
  newTag: 904a7dacbe280ee388f38a6c9cadd4a8131c8111